/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Alumnodao;
import Modelo.Alumno;
import java.awt.Font;
import java.util.Iterator;

/**
 *
 * @author dianagamboa
 */
public class venconsul extends javax.swing.JFrame {

    /**
     * Creates new form venconsul
     */
    int op;
    public venconsul() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coi = new javax.swing.JTextField();
        bcorreo = new javax.swing.JButton();
        bapellidos = new javax.swing.JButton();
        bprograma = new javax.swing.JButton();
        bfecha = new javax.swing.JButton();
        ape = new javax.swing.JTextField();
        pro = new javax.swing.JTextField();
        fec = new javax.swing.JTextField();
        bcelular = new javax.swing.JButton();
        cel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resul = new javax.swing.JTextArea();
        limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultas");

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 16)); // NOI18N
        jLabel2.setText("INSTITUTO LA FLORESTA");

        coi.setForeground(new java.awt.Color(51, 51, 51));
        coi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coiActionPerformed(evt);
            }
        });

        bcorreo.setText("Buscar por correo");
        bcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcorreoActionPerformed(evt);
            }
        });

        bapellidos.setText("Buscar por Apellidos");
        bapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bapellidosActionPerformed(evt);
            }
        });

        bprograma.setText("Buscar por programa");
        bprograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprogramaActionPerformed(evt);
            }
        });

        bfecha.setText("Buscar por fecha de nacimiento");
        bfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfechaActionPerformed(evt);
            }
        });

        ape.setForeground(new java.awt.Color(51, 51, 51));
        ape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeActionPerformed(evt);
            }
        });

        pro.setForeground(new java.awt.Color(51, 51, 51));

        fec.setText("AAAA/MM/DD");

        bcelular.setText("Buscar por celular");
        bcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcelularActionPerformed(evt);
            }
        });

        cel.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setText("Resultados");

        volver.setText("Volver al menu");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        resul.setEditable(false);
        resul.setColumns(20);
        resul.setRows(5);
        jScrollPane2.setViewportView(resul);

        limpiar.setText("Reiniciar búsqueda");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bprograma, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(bcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ape)
                                    .addComponent(pro, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(coi)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(bcelular)
                                            .addGap(32, 32, 32)
                                            .addComponent(cel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bfecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(fec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(limpiar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(volver))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bapellidos)
                    .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bprograma)
                    .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bfecha)
                    .addComponent(fec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcelular)
                    .addComponent(cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(limpiar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void limpiar() {

        resul.setText(null);
        ape.setText(null);
        fec.setText(null);
        coi.setText(null);
        cel.setText(null);
        pro.setText(null);
        
    }
    
    public void mostrar(int op){
        Alumnodao aBO = new Alumnodao();
        resul.setEditable(false);
        try {
            if (op==1){
            Alumno alumno = aBO.obtener(coi.getText());
            resul.setText(alumno.toString()); 
            } else if (op==2){
            if(!aBO.listado(ape.getText(), 1).isEmpty()) { 
            Iterator iterador = aBO.listado(ape.getText(), 1).listIterator(); //el objeto iterador que recorre el directorio
            while(iterador.hasNext()) {
                resul.append(iterador.next() + "\n"); //el método append agrega el contenido de persona al area de texto
                }
            }
            } else if (op==3){
            if(!aBO.listado(pro.getText(), 2).isEmpty()) { 
            Iterator iterador = aBO.listado(pro.getText(), 2).listIterator(); //el objeto iterador que recorre el directorio
            while(iterador.hasNext()) {
                resul.append(iterador.next() + "\n"); //el método append agrega el contenido de persona al area de texto
                }
            }
            } else if (op==4){
            if(!aBO.listado(fec.getText(), 3).isEmpty()) { 
            Iterator iterador = aBO.listado(fec.getText(), 3).listIterator(); //el objeto iterador que recorre el directorio
            while(iterador.hasNext()) {
                resul.append(iterador.next() + "\n"); //el método append agrega el contenido de persona al area de texto
                }
            }
            } else {
            if(!aBO.buscarCel(Long.parseLong(cel.getText())).isEmpty()) { 
            Iterator iterador = aBO.buscarCel(Long.parseLong(cel.getText())).listIterator(); //el objeto iterador que recorre el directorio
            while(iterador.hasNext()) {
                resul.append(iterador.next() + "\n"); //el método append agrega el contenido de persona al area de texto
                }
            }
        }
        } catch (Exception e) {
            resul.append("No hay resultados para esa consulta");
        }

    }
    
    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        ventprincipal ini= new ventprincipal();
        ini.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void apeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeActionPerformed
        
    }//GEN-LAST:event_apeActionPerformed

    private void bcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcorreoActionPerformed
        mostrar(1);
        //this.setVisible(false);
        //this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        //this.dispose();
    }//GEN-LAST:event_bcorreoActionPerformed

    private void bprogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprogramaActionPerformed
        mostrar(3);
    }//GEN-LAST:event_bprogramaActionPerformed

    private void bfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfechaActionPerformed
        mostrar(4);
    }//GEN-LAST:event_bfechaActionPerformed

    private void bcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcelularActionPerformed
        mostrar(5);
    }//GEN-LAST:event_bcelularActionPerformed

    private void bapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bapellidosActionPerformed
        mostrar(2);
    }//GEN-LAST:event_bapellidosActionPerformed
    
    private void coiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coiActionPerformed
        //TextPrompt placeholder = new TextPrompt("Ingrese el correo institucional", coi);
    }//GEN-LAST:event_coiActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venconsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venconsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venconsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venconsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venconsul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape;
    private javax.swing.JButton bapellidos;
    private javax.swing.JButton bcelular;
    private javax.swing.JButton bcorreo;
    private javax.swing.JButton bfecha;
    private javax.swing.JButton bprograma;
    private javax.swing.JTextField cel;
    private javax.swing.JTextField coi;
    private javax.swing.JTextField fec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField pro;
    private javax.swing.JTextArea resul;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
